# This is a basic workflow to help you get started with Actions

name: PublishDocumentation

# Triggered when new release is published.
on:
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_docs"
  deploy_docs:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Publish Jazzy Docs
      uses: Steven0351/publish-jazzy-docs@v1.1.1
      with:
        # Personal access token
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_JAZZY }}
